#!/bin/sh

[ -z "${IPKG_INSTROOT:-}" ] || exit 0

OPT_ROOT="${BRORAY_OPT_ROOT:-/opt}"
TMP_ROOT="${BRORAY_TMP_ROOT:-/tmp}"

"$OPT_ROOT/bin/ash" "$OPT_ROOT/broray/lib/package-setup.sh" || exit $?

rm -f \
    "$TMP_ROOT/broray-opkg-services-before-upgrade" \
    "$TMP_ROOT/broray-opkg-existing-backup" \
    "$TMP_ROOT/broray-opkg-prepared-update"
exit 0
