/** Real Chromium DOM + exact shared JS/CSS; no router or network calls. */
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import {pathToFileURL,fileURLToPath} from 'node:url';
const root=process.env.BRORAY_STAGE_ROOT || path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const prepared=process.env.BRORAY_TEST_ROOT || path.join(root,'files');
function source(rel){const p=[path.join(prepared,rel),path.join(root,'baseline',rel)].find(fs.existsSync);if(!p)throw new Error('Missing source: '+rel);return fs.readFileSync(p,'utf8');}
const js=source('runtime/app/web-new/assets/js/common.js'),css=source('runtime/app/web-new/assets/css/allpage.css');
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE?pathToFileURL(process.env.PLAYWRIGHT_MODULE).href:'playwright');
const browser=await chromium.launch({headless:true});
const results=[],repro=process.env.STAGE12_REPRO==='1';
const evidence=process.env.STAGE12_EVIDENCE || path.join(root,'evidence');fs.mkdirSync(evidence,{recursive:true});
async function setup(options={}){
 const context=await browser.newContext({viewport:options.viewport||{width:1440,height:1000},reducedMotion:options.reduced?'reduce':'no-preference'});
 await context.route('**/*',route=>route.abort());
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 let html=options.html || '<!doctype html><html><head></head><body><main class="workspace-content"><h1>Проверка уведомлений</h1><input id="focus-target"><section id="existing-error">Существующее сообщение страницы</section></main><div id="toast-root" class="toast-root" aria-live="polite" aria-atomic="true"></div></body></html>';
 html=html.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'').replace(/<link\b[^>]*>/gi,'');
 await page.setContent(html);await page.addStyleTag({content:css});
 await page.evaluate(theme=>document.documentElement.dataset.theme=theme,options.theme||'broray');
 if(!options.realTime)await page.evaluate(()=>{
  let now=0,id=0,hidden=false;const timers=new Map();
  Object.defineProperty(performance,'now',{configurable:true,value:()=>now});
  Object.defineProperty(document,'hidden',{configurable:true,get:()=>hidden});
  window.setTimeout=(fn,delay=0)=>{timers.set(++id,{fn,due:now+Number(delay)});return id;};window.clearTimeout=id=>timers.delete(id);
  window.__advance=ms=>{const end=now+ms;let count=0;while(true){const next=[...timers].sort((a,b)=>a[1].due-b[1].due)[0];if(!next||next[1].due>end)break;if(++count>100)throw new Error('Timer loop');now=next[1].due;timers.delete(next[0]);next[1].fn();}now=end;};
  window.__hidden=value=>{hidden=value;document.dispatchEvent(new Event('visibilitychange'));};window.__timers=()=>timers.size;
 });
 await page.addScriptTag({content:js});
 return {page,context,errors,toast:async(text,kind)=>page.evaluate(([text,kind])=>window.BROrayUI.toast(text,kind),[text,kind]),advance:async ms=>page.evaluate(ms=>window.__advance(ms),ms)};
}
async function check(name,fn,options={}){
 if(repro&&!name.startsWith('regression:'))return;
 const h=await setup(options);
 try{await fn(h);assert.deepEqual(h.errors,[]);results.push({name,status:'PASS'});}
 catch(error){results.push({name,status:'FAIL',error:error.message});}
 finally{await h.context.close();fs.writeFileSync(path.join(evidence,repro?'baseline-tests.json':'toast-tests.json'),JSON.stringify({tests:results,browser:browser.version(),network:'all requests blocked',routerAccessed:false,timers:'controlled except real-time case'},null,2));}
}
try{
 await check('regression: left icon and enlarged text',async({page:p,toast})=>{await toast('Настройки сохранены','success');assert.equal(await p.locator('.toast-icon').count(),1);const v=await p.evaluate(()=>{const t=document.querySelector('.toast'),i=t.querySelector('.toast-icon'),m=t.querySelector('.toast-message');return {font:parseFloat(getComputedStyle(m).fontSize),left:i.getBoundingClientRect().right<=m.getBoundingClientRect().left,width:i.getBoundingClientRect().width,weight:getComputedStyle(m).fontWeight};});assert.equal(v.font,20.8);assert.equal(v.width,48);assert.ok(v.left);assert.equal(v.weight,'700');});
 await check('regression: six seconds not four',async({page:p,toast,advance})=>{await toast('Подписка обновлена','success');await advance(4001);assert.equal(await p.locator('.toast').count(),1);await advance(1998);assert.equal(await p.locator('.toast').count(),1);await advance(1);assert.equal(await p.locator('.toast').count(),0);});
 await check('regression: errors survive transient card',async({page:p,toast,advance})=>{await toast('Не удалось обновить подписку','error');await advance(6001);assert.equal(await p.locator('.toast').count(),0);assert.equal(await p.locator('#page-notification-history').count(),1);assert.match(await p.locator('#page-notification-history').innerText(),/Не удалось обновить подписку/);});
 await check('default type remains success',async({page:p,toast})=>{await toast('Сохранено');assert.equal(await p.locator('.toast-success').count(),1);});
 await check('warning has distinct amber and exclamation',async({page:p,toast})=>{await toast('Нужна проверка','warning');assert.equal(await p.locator('.toast-warning .toast-icon path').getAttribute('d'),'M12 4v10M12 19v.2');assert.equal(await p.locator('.toast').evaluate(e=>getComputedStyle(e).borderTopColor),'rgb(225, 173, 85)');});
 await check('error red and success check not exclamation',async({page:p,toast})=>{await toast('Ошибка','error');await toast('Сохранено','success');assert.equal(await p.locator('.toast-error').evaluate(e=>getComputedStyle(e).borderTopColor),'rgb(255, 102, 120)');assert.equal(await p.locator('.toast-success path').getAttribute('d'),'M4 12l5 5L20 6');});
 await check('unknown type normalized, not a CSS injection',async({page:p,toast})=>{await toast('Информация','error injected');assert.equal(await p.locator('.toast').getAttribute('class'),'toast toast-info');assert.equal(await p.locator('.toast path').getAttribute('d'),'M12 10v9M12 5v.2');});
 await check('no close button or focus theft',async({page:p,toast})=>{await p.locator('#focus-target').focus();await toast('Внимание','warning');assert.equal(await p.locator('.toast button,.toast a,.toast [tabindex]').count(),0);assert.equal(await p.evaluate(()=>document.activeElement.id),'focus-target');assert.equal(await p.locator('.toast-icon').getAttribute('aria-hidden'),'true');});
 await check('bottom right with solid dark surface and white text',async({page:p,toast})=>{await toast('Готово','success');await p.waitForTimeout(200);const r=await p.locator('.toast').boundingBox();assert.equal(1440-r.x-r.width,18);assert.equal(1000-r.y-r.height,18);assert.equal(await p.locator('.toast').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(20, 31, 41)');assert.equal(await p.locator('.toast').evaluate(e=>getComputedStyle(e).color),'rgb(244, 248, 251)');});
 await check('text and history do not execute markup',async({page:p,toast})=>{const text='<img src=x onerror=alert(1)><script>BAD</script>& "тест"';await toast(text,'error');assert.equal(await p.locator('.toast img,.toast script,#page-notification-history img,#page-notification-history script').count(),0);assert.equal(await p.locator('.page-notification-entry span').innerText(),text);});
 await check('duplicate active message does not prolong timeout',async({page:p,toast,advance})=>{await toast('Повтор','warning');await advance(5000);await toast('Повтор','warning');assert.equal(await p.locator('.toast').count(),1);assert.equal(await p.locator('.page-notification-entry').count(),1);await advance(1000);assert.equal(await p.locator('.toast').count(),0);});
 await check('burst capped at two, evicted error remains',async({page:p,toast})=>{await toast('Первая ошибка','error');await toast('Готово 1','success');await toast('Готово 2','success');assert.equal(await p.locator('.toast').count(),2);assert.equal(await p.evaluate(()=>__timers()),2);assert.match(await p.locator('#page-notification-history').innerText(),/Первая ошибка/);});
 await check('unrelated success never clears important history',async({page:p,toast,advance})=>{await toast('Ошибка сервера','error');await advance(6000);await toast('Адрес скопирован','success');await advance(6000);assert.match(await p.locator('#page-notification-history').innerText(),/Ошибка сервера/);assert.equal(await p.locator('#existing-error').innerText(),'Существующее сообщение страницы');});
 await check('history bounded to ten distinct entries',async({page:p,toast})=>{for(let i=0;i<12;i++)await toast('Ошибка номер '+i,'error');assert.equal(await p.locator('.page-notification-entry').count(),10);assert.match(await p.locator('.page-notification-entry').first().innerText(),/номер 11/);assert.doesNotMatch(await p.locator('#page-notification-history').innerText(),/номер 0\b/);});
 await check('repeated warning stays among most recent history',async({page:p,toast})=>{await toast('Первая','warning');for(let i=0;i<9;i++)await toast('Другая '+i,'warning');await toast('Первая','warning');await toast('Последняя','warning');assert.equal(await p.locator('.page-notification-entry').count(),10);assert.match(await p.locator('#page-notification-history').innerText(),/Первая/);});
 await check('long unicode text has full retained copy',async({page:p,toast})=>{const text='🚀 Текст 東京 '.repeat(200);await toast(text,'info');assert.equal(await p.locator('.page-notification-entry span').textContent(),text);assert.ok((await p.locator('.toast-message').textContent()).length<1000);assert.equal(await p.locator('.toast-note').isVisible(),true);assert.equal(await p.locator('.toast-message').evaluate(e=>getComputedStyle(e).fontWeight),'600');});
 await check('empty messages and missing root are no-op',async({page:p,toast})=>{await toast('   ','error');await toast(null,'success');assert.equal(await p.locator('.toast').count(),0);await p.locator('#toast-root').evaluate(e=>e.remove());await toast('Не показывается','error');assert.equal(await p.locator('#page-notification-history').count(),0);});
 await check('short success does not add page history',async({page:p,toast})=>{await toast('Готово','success');assert.equal(await p.locator('#page-notification-history').count(),0);});
 await check('hidden tab pauses visible lifetime',async({page:p,toast,advance})=>{await toast('Сохранено','success');await advance(2000);await p.evaluate(()=>__hidden(true));await advance(60000);assert.equal(await p.locator('.toast').count(),1);await p.evaluate(()=>__hidden(false));await advance(3999);assert.equal(await p.locator('.toast').count(),1);await advance(1);assert.equal(await p.locator('.toast').count(),0);});
 await check('created while hidden gets six visible seconds',async({page:p,toast,advance})=>{await p.evaluate(()=>__hidden(true));await toast('Сохранено','success');assert.equal(await p.evaluate(()=>__timers()),0);await advance(60000);await p.evaluate(()=>__hidden(false));await advance(5999);assert.equal(await p.locator('.toast').count(),1);await advance(1);assert.equal(await p.locator('.toast').count(),0);});
 await check('pagehide clears timers and local history',async({page:p,toast})=>{await toast('Предупреждение','warning');await p.evaluate(()=>window.dispatchEvent(new Event('pagehide')));assert.equal(await p.evaluate(()=>__timers()),0);assert.equal(await p.locator('.toast,#page-notification-history').count(),0);await toast('Новая ошибка','error');assert.equal(await p.locator('.toast').count(),1);});
 await check('manual removal does not leave stale timer',async({page:p,toast})=>{await toast('Удалённый элемент','error');await p.locator('.toast').evaluate(e=>e.remove());await toast('Новый элемент','info');assert.equal(await p.evaluate(()=>__timers()),1);});
 await check('live region announces additions without focus',async({page:p,toast})=>{await toast('Сообщение','info');assert.equal(await p.locator('#toast-root').getAttribute('aria-live'),'polite');assert.equal(await p.locator('#toast-root').getAttribute('aria-atomic'),'false');assert.equal(await p.locator('#toast-root').getAttribute('aria-relevant'),'additions');assert.match(await p.locator('.toast-kind').textContent(),/Информация/);});
 await check('reduced motion disables entrance animation',async({page:p,toast})=>{await toast('Сохранено','success');assert.equal(await p.locator('.toast').evaluate(e=>getComputedStyle(e).animationName),'none');},{reduced:true});
 for(const theme of ['broray','night','day'])await check('readable dark card in theme '+theme,async({page:p,toast})=>{await toast('Предупреждение','warning');assert.equal(await p.locator('.toast').evaluate(e=>getComputedStyle(e).color),'rgb(244, 248, 251)');assert.equal(await p.locator('.toast').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(20, 31, 41)');},{theme});
 for(const viewport of [{width:320,height:568},{width:390,height:844},{width:812,height:375}])await check('fits viewport '+viewport.width+'x'+viewport.height,async({page:p,toast})=>{await toast('Проверка завершилась ошибкой. Обновите состояние и повторите действие.','error');await toast('Подписка обновлена. Прежние неподдержанные серверы сохранены.','warning');await p.waitForTimeout(200);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));const r=await p.locator('.toast-root').boundingBox();assert.ok(r.x>=0&&r.y>=0&&r.x+r.width<=viewport.width&&r.y+r.height<=viewport.height);if(viewport.width===390)await p.screenshot({path:path.join(evidence,'toast-mobile.png'),fullPage:true});},{viewport});
 await check('confirmation stays above notifications',async({page:p,toast})=>{await toast('Предыдущее сообщение','warning');await p.evaluate(()=>{const m=document.createElement('div');m.id='test-modal';m.className='modal-root';m.innerHTML='<div class="modal-backdrop"></div><div class="modal"><button id="confirm-test">Подтвердить</button></div>';document.body.appendChild(m);document.getElementById('confirm-test').focus();});assert.ok(await p.evaluate(()=>Number(getComputedStyle(document.getElementById('test-modal')).zIndex)>Number(getComputedStyle(document.getElementById('toast-root')).zIndex)));assert.equal(await p.evaluate(()=>document.activeElement.id),'confirm-test');await p.locator('#confirm-test').click();});
 await check('no storage or HTTP caused by notifications',async({page:p,toast})=>{await p.evaluate(()=>{window.fetch=()=>{throw new Error('Unexpected network');};Object.defineProperty(window,'localStorage',{get(){throw new Error('Unexpected storage');}});Object.defineProperty(window,'sessionStorage',{get(){throw new Error('Unexpected storage');}});});await toast('Ошибка','error');assert.equal(await p.locator('.toast').count(),1);});
 await check('apiRequest and health helpers retain behavior',async({page:p})=>{const r=await p.evaluate(async()=>{window.fetch=async(u,o)=>({ok:true,json:async()=>({u,o})});const api=await BROrayUI.apiRequest('/fixture',{body:{answer:42}});return {api,meta:BROrayUI.severityMeta('error').badgeClass,health:BROrayUI.healthIsConfirmedOk({availability:'available',severity:'ok',operational:true,consistent:true,actionRequired:false,freshness:{state:'fresh'}})};});assert.equal(r.api.o.body,'{"answer":42}');assert.equal(r.api.o.credentials,'same-origin');assert.equal(r.meta,'status-error');assert.equal(r.health,true);});
 for(const name of ['index.html','home.html','servers.html','subscriptions.html','xray.html','keenetic.html','broray.html','dns.html','routes.html','routes-import.html','routes-custom.html'])await check('shared component on actual '+name+' DOM',async({page:p,toast,advance})=>{await p.evaluate(()=>{const a=document.getElementById('app'),l=document.getElementById('page-loader');if(a)a.hidden=false;if(l)l.hidden=true;});await toast('Проверка на странице '+name,'error');assert.equal(await p.locator('.toast-icon').count(),1);assert.equal(await p.locator('.toast-message').evaluate(e=>parseFloat(getComputedStyle(e).fontSize)),20.8);await advance(6000);assert.equal(await p.locator('.toast').count(),0);assert.match(await p.locator('#page-notification-history').textContent(),new RegExp(name.replace('.','\\.')));},{html:source('runtime/app/web-new/'+name)});
 await check('real timer removes popup but retains error',async({page:p,toast})=>{await toast('Результат проверки нужно уточнить','error');await p.waitForTimeout(4200);assert.equal(await p.locator('.toast').count(),1);await p.waitForTimeout(2100);assert.equal(await p.locator('.toast').count(),0);assert.equal(await p.locator('.page-notification-entry').count(),1);},{realTime:true});
 await check('desktop evidence',async({page:p,toast})=>{await toast('Подписка обновлена. Получено 7 серверов.','success');await toast('Не удалось подготовить маршруты. Настройки не изменены.','error');await p.waitForTimeout(200);await p.screenshot({path:path.join(evidence,'toast-desktop.png'),fullPage:true});});
}finally{await browser.close();}
const report={status:results.every(t=>t.status==='PASS')?'PASS':'FAIL',passed:results.filter(t=>t.status==='PASS').length,failed:results.filter(t=>t.status==='FAIL').length,tests:results,sourceSha256:{common:crypto.createHash('sha256').update(js).digest('hex'),css:crypto.createHash('sha256').update(css).digest('hex')},browser:'Chromium',routerAccessed:false,network:'all blocked',scope:'Shared component in real DOM; actual HTML pages without page scripts. Separate regression runners load page scripts.'};
fs.writeFileSync(path.join(evidence,repro?'BASELINE-RESULT.json':'TOAST-RESULT.json'),JSON.stringify(report,null,2));
console.log(JSON.stringify(report));process.exitCode=report.failed?1:0;
