import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {pathToFileURL,fileURLToPath} from 'node:url';
const root=process.env.BRORAY_STAGE_ROOT || path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href);const browser=await chromium.launch({headless:true});const results=[];
const item={id:'qa',name:'My name',displayUrl:'provider.example.invalid',url:'https://provider.example.invalid/sub',enabled:true,autoUpdateEnabled:true,updateIntervalMinutes:360,lastUpdateStatus:'success',serversCount:1,httpUserAgent:'Client/1',providerMetadata:{schemaVersion:1,title:'Provider <img src=x>',announcement:'Message <script>bad</script>',usage:{upload:1,download:2,total:100,expire:0},supportUrl:'https://support.example.invalid',suggestedUpdateMinutes:60}};
const writes=[];const html=fs.readFileSync(path.join(root,'files/runtime/app/web-new/subscriptions.html'),'utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'');
const context=await browser.newContext({viewport:{width:1280,height:900}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('**/*',route=>{const u=new URL(route.request().url());let body='';if(u.pathname==='/subscriptions.html')return route.fulfill({status:200,contentType:'text/html',body:html});if(u.pathname==='/assets/css/allpage.css')return route.fulfill({status:200,contentType:'text/css',body:fs.readFileSync(path.join(root,'baseline/runtime/app/web-new/assets/css/allpage.css'),'utf8')});if(u.pathname.startsWith('/api/')) { if(route.request().method()==='POST'){writes.push(JSON.parse(route.request().postData()));Object.assign(item,writes.at(-1));}let data=u.pathname==='/api/session.cgi'?{ok:true,user:'QA'}:u.pathname.includes('list.cgi')?[item]:u.pathname.includes('summary.cgi')?{total:1,enabled:1,serversReceived:1,lastUpdateStatus:'success'}:item;return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({ok:true,data})});}return route.fulfill({status:204,body:''});});
async function check(name,fn){try{await fn();results.push({name,status:'PASS'});}catch(e){results.push({name,status:'FAIL',error:e.message});throw e;}}
try{
 await page.goto('http://fixture.invalid/subscriptions.html');await page.evaluate(()=>{window.BROrayUI={toast:()=>{},redirectToLogin:()=>{throw new Error('Unexpected login');}};});
 for(const name of ['subscription-provider.js','subscriptions.js'])await page.addScriptTag({content:fs.readFileSync(path.join(root,'files/runtime/app/web-new/assets/js',name),'utf8')});
 await page.locator('.subscription-card').waitFor();
 await check('metadata collapsed and literal text survives',async()=>{assert.equal(await page.locator('.subscription-provider').getAttribute('open'),null);await page.locator('.subscription-provider summary').focus();await page.keyboard.press('Enter');assert.equal(await page.locator('.subscription-provider').evaluate(e=>e.open),true);assert.match(await page.locator('.subscription-provider').innerText(),/Provider <img src=x>/);assert.equal(await page.locator('.subscription-provider img,.subscription-provider script').count(),0);});
 await check('link has noopener and user settings untouched',async()=>{assert.match(await page.locator('.subscription-provider a').getAttribute('rel'),/noopener/);assert.match(await page.locator('.subscription-card h2').innerText(),/My name/);assert.match(await page.locator('.subscription-card-meta').first().innerText(),/360/);});
 await check('edit loads existing user agent and submits exact value',async()=>{await page.locator('[data-action="edit"]').click();await page.locator('#subscription-user-agent').waitFor({state:'attached'});await page.locator('#subscription-form-panel details summary').click();await page.waitForFunction(()=>document.getElementById('subscription-user-agent').value==='Client/1');await page.locator('#subscription-user-agent').fill('AnotherClient/2');await page.locator('#subscription-submit').click();await page.waitForFunction(()=>document.getElementById('subscription-form-panel').hidden);assert.equal(writes.length,1);assert.equal(writes[0].httpUserAgent,'AnotherClient/2');});
 await check('new form restores automatic user agent',async()=>{await page.locator('#add-subscription').click();assert.equal(await page.locator('#subscription-user-agent').inputValue(),'');await page.locator('#subscription-cancel').click();assert.equal(writes.length,1);});
 await check('invalid user agent blocked by browser form',async()=>{await page.locator('#add-subscription').click();await page.locator('#subscription-user-agent').fill('кириллица');assert.equal(await page.locator('#subscription-user-agent').evaluate(e=>e.checkValidity()),false);await page.locator('#subscription-cancel').click();});
 await check('mobile content fits width',async()=>{await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+2));await page.screenshot({path:path.join(root,'evidence/subscriptions-mobile.png'),fullPage:true});});
 await check('no JavaScript runtime errors',async()=>assert.deepEqual(errors,[]));
}finally{fs.writeFileSync(path.join(root,'evidence/browser-results.json'),JSON.stringify({tests:results,browser:browser.version(),routerAccessed:false,http:'intercepted fixtures',globalShell:'stubbed BROrayUI, only subscriptions scripts loaded'},null,2));await browser.close();}
console.log(JSON.stringify({passed:results.filter(t=>t.status==='PASS').length,failed:results.filter(t=>t.status==='FAIL').length}));
