import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import assert from 'node:assert/strict';import test from 'node:test';import {fileURLToPath} from 'node:url';
const root=process.env.BRORAY_TEST_ROOT || path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const code=fs.readFileSync(path.join(root,'runtime/app/web-new/assets/js/subscription-provider.js'),'utf8');const ctx={window:{},URL};vm.runInNewContext(code,ctx);const api=ctx.window.BRORAYSubscriptionProvider;
const render=(p,status='success')=>api.render({providerMetadata:{schemaVersion:1,...p},lastUpdateStatus:status});
test('absent metadata renders nothing',()=>assert.equal(api.render({}),''));
test('metadata collapsed by default',()=>{const s=render({title:'Provider'});assert.match(s,/<details/);assert.doesNotMatch(s,/<details[^>]*open/);});
test('provider strings escaped',()=>{const s=render({title:'<img src=x onerror=alert(1)>',announcement:'<script>bad</script>'});assert.doesNotMatch(s,/<img|<script>/);assert.match(s,/&lt;img/);});
test('manual setting explanatory text',()=>assert.match(render({suggestedUpdateMinutes:60}),/Ваш интервал не изменён/));
test('zero limit not called unlimited',()=>assert.match(render({usage:{total:0}}),/не указал лимит/));
test('zero expiry not 1970',()=>assert.doesNotMatch(render({usage:{expire:0}}),/1970/));
test('unknown counters not fabricated',()=>assert.doesNotMatch(render({usage:{download:1,total:100}}),/Осталось/));
test('remaining cannot go negative',()=>assert.match(render({usage:{upload:100,download:50,total:10}}),/Осталось<\/dt><dd>0 Б/));
test('unsafe integer not displayed',()=>assert.doesNotMatch(render({usage:{download:Number.MAX_SAFE_INTEGER+1},title:'P'}),/Получено/));
test('failed update marks cached info',()=>assert.match(render({title:'P'},'error'),/не подтверждены/));
test('running update marks cached info',()=>assert.match(render({title:'P'},'running'),/не подтверждены/));
test('success not labelled failure',()=>assert.doesNotMatch(render({title:'P'}),/не подтверждены/));
test('links opt in and isolated',()=>{const s=render({supportUrl:'https://support.example.invalid/?q="'});assert.match(s,/noopener noreferrer/);assert.match(s,/target="_blank"/);assert.doesNotMatch(s,/q=""/);});
for(const u of ['javascript:alert(1)','data:text/html,hello','file:///secret','https://user:secret@example.com','//example.com','\nhttps://example.com'])test('unsafe URL '+u.slice(0,20),()=>assert.equal(api.safeLink(u),''));
test('normal HTTPS link accepted',()=>assert.equal(api.safeLink('https://example.com'),'https://example.com/'));
test('invalid fields not exposed verbatim',()=>{const s=render({invalidFields:['PRIVATE_CANARY']});assert.doesNotMatch(s,/PRIVATE_CANARY/);assert.match(s,/неверный формат/);});
test('ignored directives not executed',()=>assert.match(render({ignoredDirectives:['routing']}),/не применяются/));
test('oversized announcement ignored',()=>assert.equal(render({announcement:'x'.repeat(1025)}),''));
test('reloading resets new UA field via form.reset contract',()=>{const s=fs.readFileSync(path.join(root,'runtime/app/web-new/assets/js/subscriptions.js'),'utf8');assert.match(s,/form.reset\(\)/);assert.match(s,/httpUserAgent: byId\("subscription-user-agent"\).value/);});
