const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict'),test=require('node:test'),path=require('path');
const source=fs.readFileSync(path.join(__dirname,'../runtime/app/web-new/assets/js/broray.js'),'utf8');
function extract(name){const re=new RegExp('^    (?:async )?function '+name+'\\(', 'm');const start=source.search(re);assert(start>=0,name);const end=source.slice(start+1).search(/^    (?:async )?function /m);return source.slice(start,end<0?undefined:start+1+end);}
function fixture(){const nodes={},timers=[],messages=[];const state={busy:false,pollTimer:null,pollInFlight:false,pollFailures:0,operationId:null,operationKind:null,unconfirmedPolls:0};let reply={ok:true,operationId:null,state:'idle',running:false};
const c={state,Date,window:{setTimeout(fn,ms){timers.push({fn,ms});return timers.length;},clearTimeout(){}},byId(id){return nodes[id]??={setAttribute(){}};},setText(id,v){this.byId(id).textContent=v;},setBusy(v){state.busy=v;},setButtonBusy(){},applyControlState(){},operationLabel:x=>x,hidePageError(){},showPageError:x=>messages.push(x),toast(){},errorMessage:e=>e.message,loadInfo:async()=>({}),request:async(url)=>{if(url.includes('uninstall.cgi'))return {ok:true,accepted:true,operation:'uninstall',operationId:'accepted-1'};if(reply instanceof Error)throw reply;return reply;}};
c.setText=(id,v)=>{c.byId(id).textContent=v;};vm.createContext(c);
for(const n of ['renderOperation','loadOperation','renderPollingInterruption','schedulePolling','pollOperation','startPolling','stopPolling','startAction'])vm.runInContext(extract(n),c);
return {c,state,timers,messages,nodes,setReply(v){reply=v;}};}
test('accepted removal stays tracked across idle and unrelated success',async()=>{const f=fixture();await f.c.startAction('/api/broray/uninstall.cgi','started',{},null,'delete');assert.equal(f.state.operationId,'accepted-1');assert.equal(f.state.busy,true);assert(f.timers.length>0);f.setReply({operationId:'old',state:'success',running:false});await f.c.pollOperation();assert.equal(f.state.busy,true);f.setReply({operationId:'accepted-1',state:'success',running:false});await f.c.pollOperation();assert.equal(f.state.busy,false);});
test('removed WebUI ends bounded polling as unconfirmed, never success',async()=>{const f=fixture();await f.c.startAction('/api/broray/uninstall.cgi','started',{},null,'delete');f.setReply(new Error('Failed to fetch'));for(let i=0;i<6;i++){f.state.pollTimer=null;await f.c.pollOperation();}assert.equal(f.state.busy,false);assert.equal(f.state.pollTimer,null);assert.match(f.messages.at(-1),/не подтвержд/);assert(!f.messages.at(-1).includes('перезапускается'));assert.equal(f.state.operationId,'accepted-1');});
test('idle cannot poll forever after accepted response',async()=>{const f=fixture();await f.c.startAction('/api/broray/uninstall.cgi','started',{},null,'delete');for(let i=0;i<15;i++){f.state.pollTimer=null;await f.c.pollOperation();}assert.equal(f.state.busy,false);assert.equal(f.state.pollTimer,null);assert.match(f.messages.at(-1),/не подтвержд/);});
