import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {pathToFileURL,fileURLToPath} from 'node:url';
const root=process.env.BRORAY_STAGE_ROOT || path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href);const browser=await chromium.launch({headless:true});const results=[];
const item={id:'qa',name:'My name',displayUrl:'provider.example.invalid',url:'https://provider.example.invalid/sub',enabled:true,autoUpdateEnabled:true,updateIntervalMinutes:360,lastUpdateStatus:'success',serversCount:1,httpUserAgent:'Client/1',providerMetadata:{schemaVersion:1,title:'Provider <img src=x>',announcement:'Message <script>bad</script>',usage:{upload:1,download:2,total:100,expire:0},supportUrl:'https://support.example.invalid',suggestedUpdateMinutes:60}};
const writes=[];const html=fs.readFileSync(path.join(root,'files/runtime/app/web-new/subscriptions.html'),'utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'');
const context=await browser.newContext({viewport:{width:1280,height:900}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('**/*',route=>{const u=new URL(route.request().url());let body='';if(u.pathname==='/subscriptions.html')return route.fulfill({status:200,contentType:'text/html',body:html});if(u.pathname==='/assets/css/allpage.css')return route.fulfill({status:200,contentType:'text/css',body:fs.readFileSync(path.join(root,'baseline/runtime/app/web-new/assets/css/allpage.css'),'utf8')});if(u.pathname.startsWith('/api/')) { if(route.request().method()==='POST'){writes.push(JSON.parse(route.request().postData()));Object.assign(item,writes.at(-1));}let data=u.pathname==='/api/session.cgi'?{ok:true,user:'QA'}:u.pathname.includes('list.cgi')?[item]:u.pathname.includes('summary.cgi')?{total:1,enabled:1,serversReceived:1,lastUpdateStatus:'success'}:item;return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({ok:true,data})});}return route.fulfill({status:204,body:''});});
async function check(name,fn){try{await fn();results.push({name,status:'PASS'});}catch(e){results.push({name,status:'FAIL',error:e.message});throw e;}}
try{
 await page.goto('http://fixture.invalid/subscriptions.html');await page.evaluate(()=>{window.BROrayUI={toast:()=>{},redirectToLogin:()=>{throw new Error('Unexpected login');}};});
 for(const name of ['subscription-provider.js','subscriptions.js']){let f=path.join(root,'files/runtime/app/web-new/assets/js',name);if(!fs.existsSync(f))f=path.join(root,'baseline/runtime/app/web-new/assets/js',name);await page.addScriptTag({content:fs.readFileSync(f,'utf8')});}
 await page.locator('.subscription-card').waitFor();
 await check('legacy subscription defaults to no disclosure',async()=>{await page.locator('[data-action="edit"]').click();await page.locator('#subscription-device-info').waitFor();assert.equal(await page.locator('#subscription-device-info').isChecked(),false);assert.equal(writes.length,0);});
 await check('privacy explanation includes HWID and retained provider records',async()=>{const text=await page.locator('#subscription-device-info-hint').innerText();assert.match(text,/HWID/);assert.match(text,/MAC/);assert.match(text,/не удаляет/);assert.equal(await page.locator('#subscription-device-info').getAttribute('aria-describedby'),'subscription-device-info-hint');});
 await check('keyboard opt-in submits only boolean not browser identity',async()=>{await page.locator('#subscription-device-info').focus();await page.keyboard.press('Space');assert.equal(await page.locator('#subscription-device-info').isChecked(),true);await page.locator('#subscription-submit').click();await page.waitForFunction(()=>document.getElementById('subscription-form-panel').hidden);assert.equal(writes.length,1);assert.equal(writes[0].sendDeviceInfo,true);assert.deepEqual(Object.keys(writes[0]).sort(),['name','url','httpUserAgent','sendDeviceInfo','updateIntervalMinutes','enabled','autoUpdateEnabled'].sort());});
 await check('edit reloads enabled setting',async()=>{await page.locator('[data-action="edit"]').click();await page.waitForFunction(()=>document.getElementById('subscription-device-info').checked);assert.equal(await page.locator('#subscription-device-info').isChecked(),true);});
 await check('cancel does not change provider setting',async()=>{await page.locator('#subscription-device-info').uncheck();await page.locator('#subscription-cancel').click();assert.equal(writes.length,1);await page.locator('[data-action="edit"]').click();await page.waitForFunction(()=>document.getElementById('subscription-device-info').checked);});
 await check('opt-out persists false',async()=>{await page.locator('#subscription-device-info').uncheck();await page.locator('#subscription-submit').click();await page.waitForFunction(()=>document.getElementById('subscription-form-panel').hidden);assert.equal(writes.length,2);assert.equal(writes[1].sendDeviceInfo,false);});
 await check('new subscription starts unchecked',async()=>{await page.locator('#add-subscription').click();assert.equal(await page.locator('#subscription-device-info').isChecked(),false);await page.locator('#subscription-name').fill('New');await page.locator('#subscription-url').fill('https://provider.example.invalid/new');await page.locator('#subscription-immediate').uncheck();await page.locator('#subscription-submit').click();await page.waitForFunction(()=>document.getElementById('subscription-form-panel').hidden);assert.equal(writes.length,3);assert.equal(writes[2].sendDeviceInfo,false);});
 await check('new opt-in independent from Android user agent',async()=>{await page.locator('#add-subscription').click();await page.locator('#subscription-name').fill('Router');await page.locator('#subscription-url').fill('https://provider.example.invalid/new');await page.locator('#subscription-device-info').check();await page.locator('#subscription-form-panel details summary').click();await page.locator('#subscription-user-agent').fill('Android-compat/1');await page.locator('#subscription-submit').click();await page.waitForFunction(()=>document.getElementById('subscription-form-panel').hidden);assert.equal(writes[3].sendDeviceInfo,true);assert.equal(writes[3].httpUserAgent,'Android-compat/1');assert.equal(writes[3].deviceModel,undefined);});
 await check('no JavaScript runtime errors',async()=>assert.deepEqual(errors,[]));
}finally{fs.writeFileSync(path.join(root,'evidence/browser-device-results.json'),JSON.stringify({tests:results,browser:browser.version(),routerAccessed:false,http:'intercepted fixtures',globalShell:'stubbed BROrayUI; subscription form only'},null,2));await browser.close();}
console.log(JSON.stringify({passed:results.filter(t=>t.status==='PASS').length,failed:results.filter(t=>t.status==='FAIL').length}));
