#!/opt/bin/ash
ENABLED="${BRORAY_MONITOR_ENABLED:-yes}"
BRORAY_ROOT="${BRORAY_MONITOR_ROOT:-${BRORAY_ROOT:-/opt/broray}}"
BRORAY_OPS_ASH="${BRORAY_MONITOR_ASH:-${BRORAY_OPS_ASH:-/opt/bin/ash}}"
export BRORAY_ROOT BRORAY_OPS_ASH
action="${1:-}"
case "$action" in
  check) action=status ;;
  start) [ "$ENABLED" = yes ] || exit 0 ;;
  stop|restart|status) ;;
  *) exit 64 ;;
esac
exec "$BRORAY_OPS_ASH" "$BRORAY_ROOT/bin/broray-service" connection-monitor "$action"
