#!/opt/bin/ash
ENABLED=yes
ROOT="${BRORAY_ROOT:-/opt/broray}"
ASH="${BRORAY_OPS_ASH:-/opt/bin/ash}"
case "${1:-}" in
    start|stop|restart|status)
        exec "$ASH" "$ROOT/bin/broray-service" subscriptions "$1" ;;
    *) exit 64 ;;
esac
