server.modules = (
    "mod_cgi"
)

server.document-root = "/opt/broray/web"
server.port = 8080

server.pid-file = "/opt/broray/run/lighttpd.pid"
server.errorlog = "/opt/broray/logs/lighttpd-error.log"

index-file.names = ( "index.html" )

mimetype.assign = (
    ".html" => "text/html; charset=utf-8",
    ".css"  => "text/css",
    ".js"   => "application/javascript",
    ".json" => "application/json"
)

cgi.assign = (
    ".cgi" => ""
)

static-file.exclude-extensions = (
    ".cgi"
)
